apiVersion: batch/v1
kind: CronJob
metadata:
  name: monitor-pod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: test
          containers:
          - name: monitor-pod
            image: bitnami/kubectl:latest
            command: ["/bin/bash","-c"]
            args:
                - POD_NAME=$(kubectl get pods -o=jsonpath='{range .items[?(@.status.containerStatuses[*].state.waiting.reason=="ImagePullBackOff")]}{.metadata.name}{"\n"}{end}');
                  kubectl delete pod $POD_NAME;sleep 10;M_POD_NAME=$(kubectl get pods | grep monitor-pod-* | awk '{print $1}');kubectl delete pod $M_POD_NAME;

          restartPolicy: OnFailure
